# NumPy

### Creating NumPy Array

In [6]:
import numpy as np

In [14]:
## 1D Array Vector

a = np.array([1,2,3,4,5])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [18]:
# 2D Array (matrix)

a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# 3D Array

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #tensor
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
# dtype
np.array([1,2,3,4,5],dtype = float)

array([1., 2., 3., 4., 5.])

In [24]:
# dtype
np.array([1,2,3,4,5],dtype = bool)

array([ True,  True,  True,  True,  True])

In [26]:
# dtype
np.array([1,2,3,4,5],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [28]:
# A range
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# A range
np.arange(1,11,3)           #skipping function

array([ 1,  4,  7, 10])

In [32]:
# Reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
# Reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [36]:
# Reshape
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
# Reshape
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# 4D

# Reshape
np.arange(16).reshape(2,2,2,2)

# ZEROS AND ONES

In [43]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# RANDOM

In [50]:
np.random.random((3,4))

array([[0.85113236, 0.94098479, 0.60614785, 0.49800498],
       [0.1573968 , 0.73821137, 0.64915533, 0.35837465],
       [0.69394922, 0.86824364, 0.30601586, 0.55508703]])

# LIN SPACE

In [55]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [57]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

# IDENTITY ARRAY

In [60]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# ARRAY ATTRIBUTES

In [67]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
# ndim
a3.ndim

3

In [72]:
# shape 
a2.shape

(3, 4)

In [90]:
# size 
print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [96]:
# item size 
print(a1.itemsize)
a1

4


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
int32
int32


# CHANGING DATATYPE

In [112]:
# astype

a3.astype(np.int64)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ARRAY OPERATIONS 

In [115]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [118]:
# Scalar Operation 

a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [120]:
# Scalar Operation 

a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [124]:
# Vector Opeartion

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [126]:
# Vector Opeartion

a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [130]:
# Relational Operator

a2 < 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [132]:
# Relational Operator

a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])